# Site settings
title:
email: lantoniotrento@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "https://antfolio.github.io" # the subpath of your site, e.g. /blog/
url: "/antfolio.github.io" # the base hostname & protocol for your site

twitter_username: officialtrento
github_username: antoniotrento
linkedin_username: antoniotrento

# Build settings
markdown: kramdown
